"""initial_schema

Revision ID: aaabc02bf9db
Revises: 
Create Date: 2026-04-29 17:05:37.998530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaabc02bf9db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('documents', sa.Column('last_event', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()))

    # Alter the NOT NULL constraints after setting defaults
    op.alter_column('documents', 'retry_count', nullable=False)
    op.alter_column('documents', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'last_error')
    op.drop_column('documents', 'last_event')
    op.drop_column('documents', 'retry_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
